apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: kabanero-website
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - name: kabanero-website
    template:
      name: kabanero-website